name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      api-key: ${{ secrets.NUGET_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.100-preview.3.21202.5
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Add NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/JustinBritt/index.json --name GitHub
    - name: Publish NuGet Package
      run: dotnet nuget push D:\a\DiscreteHalfNormal\DiscreteHalfNormal\DiscreteHalfNormal\bin\Release\DiscreteHalfNormal.0.0.1.nupkg --source "GitHub" --api-key api-key
