name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.3.21202.5
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet Package
      run: dotnet nuget push /home/runner/work/DiscreteHalfNormal/DiscreteHalfNormal/DiscreteHalfNormal/bin/Release/DiscreteHalfNormal.0.0.1.nupkg --source https://nuget.pkg.github.com/JustinBritt/index.json --api-key ${{secrets.NUGET_API_KEY}}
